name: Integration

on: pull_request

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using Nodejs
        uses: actions/setup-node@v2
        with: 22.
        name: Install dependencies, run tests and build
        run: |
          npm install
          npm run test
          npm run build
          